Time::DATE_FORMATS[:default] = '%-m/%-d %H:%M'
Time::DATE_FORMATS[:datetime] = '%Y/%-m/%-d %H:%M'
Time::DATE_FORMATS[:year] = '%Y/%-m/%-d'
Time::DATE_FORMATS[:month] = '%-m月%-d日'
Time::DATE_FORMATS[:time] = '%H:%M'
Date::DATE_FORMATS[:default] = '%Y/%-m/%-d'
Date::DATE_FORMATS[:year] = '%Y/%-m'
Date::DATE_FORMATS[:month] = '%-m/%-d'